---@type NvPluginSpec
-- NOTE: Code Outline
return {
  "stevearc/aerial.nvim",
  event = { "BufReadPost", "BufNewFile" },
  opts = {
    attach_mode = "global",
    backends = { "lsp", "treesitter", "markdown" },
    layout = {
      max_width = { 60, 0.2 },
      min_width = 20,
      default_direction = "right",
      wrap_length = nil,
      pad_left = 0,
    },
    show_symbols = {
      in_window = {
        max_lines = nil,
        min_symbol_width = nil,
        padding = { left = 2, right = 0 },
        border = "rounded",
        title_border = "rounded",
        border_chars = { "─", "│", "─", "│", "╭", "╮", "╯", "╰" },
        border_hl = "FloatBorder",
        title_hl = "FloatTitle",
        symbols_hl = nil,
        icon_position_y = "top",
        icons = {
          File = "󰈔 ",
          Module = "󰕳 ",
          Namespace = "󰕳 ",
          Package = "󰕳 ",
          Class = "󰠱 ",
          Method = "󰊕 ",
          Property = "󰜢 ",
          Field = "󰜢 ",
          Constructor = " ",
          Enum = "󰕳 ",
          Interface = "󰕳 ",
          Function = "󰊕 ",
          Variable = "󰀫 ",
          Constant = "󰏿 ",
          String = "󰀬 ",
          Boolean = "󰨙 ",
          Number = "󰎠 ",
          Null = "󰕳 ",
          Object = "󰕳 ",
          Key = "󰕳 ",
          Struct = "󰠱 ",
          Event = "󰕳 ",
          Operator = "󰕳 ",
          TypeParameter = "󰕳 ",
        },
      },
    },
    filters = {
      default = {
        "EmptyGroup",
        "DuplicateNested",
      },
    },
    render = {
      max_depth = nil,
      highlight_hovered_item = true,
      highlight_symbol_at_cursor = true,
      signs = true,
      symbols_hl = "AerialSymbol",
    },
    close = {
      on_select = false,
      on_navigation = false,
    },
    anchor = {
      max_width = nil,
      max_height = nil,
      default_direction = nil,
    },
    update_events = "CursorHold,InsertLeave",
    close_on_select = false,
    auto_close = true,
    autojump = true,
    symbols = nil,
    filter_kind = false,
    icons = nil,
    keymaps = {
      ["<CR>"] = "actions.ret",
      ["<2-LeftMouse>"] = "actions.ret",
      ["<C-v>"] = "actions.vsplit",
      ["<C-s>"] = "actions.split",
      ["<C-]>"] = "actions.tcd",
      ["<C-t>"] = "actions.tabfor",
      ["q"] = "actions.close",
      ["o"] = "actions.tree_toggle",
      ["["] = "actions.prev",
      ["]"] = "actions.next",
      ["<"] = "actions.prev_up",
      [">"] = "actions.next_up",
      ["{"] = "actions.prev_up",
      ["}"] = "actions.next_up",
      ["g?"] = "actions.help",
    },
  },
  init = function()
    vim.keymap.set("n", "<leader>co", "<cmd>AerialToggle!<CR>", { desc = "Aerial | Toggle Outline", silent = true })
    vim.keymap.set("n", "<leader>cO", "<cmd>AerialToggle! right<CR>", { desc = "Aerial | Toggle Outline Right", silent = true })
  end,
}
